<a href="https://colab.research.google.com/github/Igor69-web/PrOA-Lab1/blob/main/%D0%9B%D0%B0%D0%B11_%D0%91%D1%83%D1%86_%D0%98_%D0%94_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание 1.1

In [ ]:
import numpy as np
n = int(input("n="))
z = np.zeros(n)
print(z)


n=5
[0. 0. 0. 0. 0.]


Задание 1.2

In [ ]:
import numpy as np
a = np.zeros((10,10))
z= a.size*a.itemsize
print(z)
b = np.array([1,2,3],dtype = np.float64)
v = b.size*b.itemsize
print(v)

800
24


Задание 1.3

In [ ]:
import numpy as np
n = int(input("n="))
x = int(input("x="))
z = np.zeros(n)
z[x]=1
print(z)

n=10
x=4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Задание 1.4

In [ ]:
import numpy as np
n = int(input("n="))
m = int(input("m="))
z = np.arange(n,m+1)
print(z)

n=1
m=5
[1 2 3 4 5]


Задание 1.5

In [1]:
import numpy as np
z = np.array([1,2,3,4])
print(z)
reversed_arr = np.flipud(z)
print(reversed_arr)

[1 2 3 4]
[4 3 2 1]


Задание 1.6

In [ ]:
import numpy as np
n = int(input("n="))
m = int(input("строк="))
k = int(input("столбцов="))
z = np.arange(n).reshape(m,k)
print(z)



n=9
строк=3
столбцов=3
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Задание 1.7

In [ ]:
import numpy as np
z = np.array([1,0,2,0,3,0,4])
np.nonzero(z)


(array([0, 2, 4, 6]),)

Задание 1.8

In [ ]:
import numpy as np
n = int(input("n="))
z = np.eye(n)
print(z)

n=3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Задаие 1.9

In [ ]:
import numpy as np
n = int(input("n="))
m = int(input("m="))
l = int(input("l="))
np.random.seed(42)
z = np.array(n*m*l)
np.random.rand(z).reshape(4,2)


n=2
m=2
l=2


array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615]])

Задание 1.10

In [ ]:
import numpy as np
n = int(input("n="))
m = int(input("m="))
np.random.seed(42)
z = np.random.rand(m*n)
max = np.max(z)
min = np.min(z)
print(max,'\n',min)

n=10
m=10
0.9868869366005173 
 0.005522117123602399


Задание 1.11

In [ ]:
import numpy as np
n = int(input("n="))
m = int(input("m="))
np.random.seed(42)
z = np.random.rand(m*n)
b = np.mean(z)
print(b)

n=12
m=6
0.46798212705144554


Задание 1.12

In [ ]:
import numpy as np
A = np.array([1.5, 2.5, 3.5])
B = np.array([4, 5, 6])
np.dot(A, B, out=None)

39.5

Задание 1.13

In [ ]:
import numpy as np
A = np.array([
 [1, 2, 3],
 [4, 5, 6]
])
B = np.array([
 [11.5],
 [12.5],
 [13.5]
])
Z = np.dot(A,B)
if Z == True:
    print(Z)
else:
    print("Упс! Что-то пошло не так...")


ValueError: ignored

Задание 1.14

In [ ]:
import numpy as np
z = np.arange(11)
print(z)
z[(z>=4) & (z<=8)] *= -1
print(z)

b = np.array([-10,-5,0,5,10])
b[b==5]=-5
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]
[-10  -5   0  -5  10]


Задание 1.15

In [ ]:
import numpy as np
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 0, 4]])
print(X)
diag = np.diagonal(X)
x = diag[diag!=0]
x = np.prod(x)
print(x)

[[1 0 1]
 [2 0 2]
 [3 0 3]
 [4 0 4]]
3


Задание 1.16

In [ ]:
import numpy as np
n = int(input("n="))
z = np.zeros(n)
print(z)

n=5
[0. 0. 0. 0. 0.]


Задание 1.17

In [ ]:
import numpy as np
z = np.zeros([10,10])
z = z.size*z.itemsize
print(z)
z = np.array([1,2,3], dtype=np.float64)
z = z.size*z.itemsize
print(z)

800
24


Задание 1.18

In [ ]:
import numpy as np
n = int(input("n="))
x = int(input("x="))
z = np.zeros(n)
z[x] = 1
print(z)


n=10
x=4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Задание 1.19

In [ ]:
import numpy as np
n = int(input("n="))
m = int(input("m="))
z = np.arange(n,m+1)
print(z)

n=10
m=50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Задание 1.20

In [ ]:
import numpy as np
z = np.array([1, 2, 3, 4])
np.flip(z)

array([4, 3, 2, 1])

Задание 1.21

In [ ]:
import numpy as np
n = int(input("n="))
m = int(input("m="))
k = int(input("k="))
z = np.arange(n).reshape(m,k)
print(z)

n=9
m=3
k=3
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Задание 1.22

In [ ]:
import numpy as np
z = np.array([1, 0, 2, 0, 3, 0, 4])
NoneZeros = np.nonzero(z)
print(NoneZeros)

(array([0, 2, 4, 6]),)


Задание 1.23

In [ ]:
import numpy as np
n = int(input("n="))
z = np.eye(n)
print(z)

n=3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Задание 1.24

In [ ]:
import numpy as np
n = int(input("n="))
m = int(input("m="))
l = int(input("l="))
np.random.seed(42)
z = np.array(n*m*l)
np.random.rand(z).reshape(n*m,l)



n=2
m=2
l=2


array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615]])

Задание 1.25

In [ ]:
import numpy as np
n = int(input("n="))
m = int(input("m="))
np.random.seed(42)
z = np.random.rand(n*m)
max = np.min(z)
min = np.max(z)
print(max,'\n',min)

n=10
m=10
0.005522117123602399 
 0.9868869366005173
